ofed_switcher.configuration:
  type: config_object
  label: 'Openfed switcher settings'
  mapping:
    backend:
      type: string
      label: 'Backend path'
    frontend:
      type: string
      label: 'Frontend path'
