# Schema for the configuration files of the Disable route normalizer module.

disable_route_normalizer.settings:
  type: config_entity
  label: 'Disable route normalizer settings'
  mapping:
    route_ignore_neutral_nodes:
      type: boolean
      label: 'Ignore nodes with undefined or without language.'
