alertbox.settings:
  type: config_object
  label: 'Alertbox settings'
  mapping:
    alertbox_allow_hide:
      type: boolean
      label: 'Option to allow hiding the alertbox'
    alertbox_default_mode:
      type: boolean
      label: 'Option to use Drupal''s default block management system'
    alertbox_label_close:
      type: label
      label: 'Label for the close button'
    alertbox_label_dismiss:
      type: label
      label: 'Label for the dismiss button'
